### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by codemakerlive** [twolfson/css-validator#2]
Are you interested in expanding to tool to include a binary for command-line interface?

**Comment by twolfson** [comment]
I am open to supporting this but could you explain your use case further?

This library is mostly a call out to a hosted service. That service provides a `.jar`file that can be downloaded/run locally. This tool is mostly to provide a nice interface for `node`, not really CLI territory =/

https://jigsaw.w3.org/css-validator/DOWNLOAD.html

**Comment by codemakerlive** [comment]
You're right and I ended up writing something small myself for CLI validation. Thanks for the support.

**Comment by twolfson** [comment]
Cool, glad to hear it worked out =)
